# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 06:11
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='numero')),
                ('fecha_entrada', models.DateTimeField(verbose_name='fecha de entrada')),
                ('fecha_salida', models.DateTimeField(verbose_name='fecha de salida')),
                ('observaciones', models.TextField(verbose_name='observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(unique=True, verbose_name='n\xfamero')),
                ('marca', models.CharField(max_length=50, verbose_name='marca')),
                ('modelo', models.IntegerField(verbose_name='modelo')),
                ('serie', models.CharField(max_length=18, unique=True, verbose_name='serie')),
                ('millaje', models.IntegerField(default=0, verbose_name='millaje')),
                ('placa', models.CharField(max_length=8, unique=True, verbose_name='placa')),
                ('tag', models.IntegerField(help_text='N\xfamero de serie Tarjeta de cruze (Ida)', verbose_name='TAG')),
                ('decal', models.IntegerField(help_text='N\xfamero de serie Tarjeta de cruze (Regreso)', verbose_name='DECAL')),
                ('estado', models.CharField(choices=[('0', 'Libre'), ('1', 'Ocupado'), ('2', 'Arrendado')], default=0, max_length=2, verbose_name='estado')),
                ('circulacion', models.CharField(max_length=20, verbose_name='circulaci\xf3n')),
                ('expira_circulacion', models.DateField(verbose_name='vencimiento de circulaci\xf3n')),
            ],
            options={
                'verbose_name': 'Camion',
                'verbose_name_plural': 'Camiones',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pais', models.CharField(choices=[('US', 'United States'), ('MX', 'Mexico'), ('CA', 'Canada')], max_length=20, verbose_name='pa\xeds')),
                ('estado', models.CharField(max_length=20, verbose_name='estado')),
                ('direccion', models.CharField(max_length=70, verbose_name='direcci\xf3n')),
                ('cpostal', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='C\xf3digo postal invalido. xxxx-xxxxx', regex='^\\+?1?\\d{4,5}$')], verbose_name='c\xf3digo postal')),
                ('rfc', models.CharField(help_text='Registro Federal de Contribuyentes', max_length=13, validators=[django.core.validators.RegexValidator(message='C\xf3digo RFC invalido', regex='^([A-Z\xd1&]{3,4}) ?(?:- ?)?(\\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\\d|3[01])) ?(?:- ?)?([A-Z\\d]{2})([A\\d])$')], verbose_name='RFC')),
                ('telefono', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='N\xfamero de telefono invalido. (xxx)-xxx-xxxx', regex='^\\+?1?\\d{10}$')], verbose_name='tel\xe9fono')),
                ('descripcion', models.TextField(verbose_name='descripcion')),
                ('tax', models.CharField(max_length=45, verbose_name='tax')),
                ('credito', models.IntegerField(verbose_name='credito')),
                ('facturacion', models.IntegerField(verbose_name='facturaci\xf3n')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consignatario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Cliente')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contactos_Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contacto', models.CharField(max_length=50, verbose_name='contacto')),
                ('tipo', models.CharField(choices=[('IMP', 'Importaci\xf3n'), ('EXP', 'Exportaci\xf3n'), ('FACMX', 'Facturaci\xf3n MX'), ('FACUS', 'Facturaci\xf3n US')], max_length=20, verbose_name='tipo')),
                ('telefono', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='N\xfamero de telefono invalido. (xxx)-xxx-xxxx', regex='^\\+?1?\\d{10}$')], verbose_name='telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='correo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Despachador_Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='contacto')),
                ('radio', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='N\xfamero de radio invalido. xxxx*xxxxxxxx*xxxxxxxx', regex='^([1-9]{1,4})$')], verbose_name='radio')),
                ('telefono', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='N\xfamero de telefono invalido. (xxx)-xxx-xxxx', regex='^\\+?1?\\d{10}$')], verbose_name='telefono')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Ejecutivo_Consignatario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70, verbose_name='ejecutivo')),
                ('telefono', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='N\xfamero de telefono invalido. (xxx)-xxx-xxxx', regex='^\\+?1?\\d{10}$')], verbose_name='telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='correo')),
                ('consignatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Consignatario')),
            ],
        ),
        migrations.CreateModel(
            name='Flujo_Trabajo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('ip', models.GenericIPAddressField()),
                ('modulo', models.CharField(max_length=250)),
                ('navegador', models.CharField(max_length=250)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inspeccion_Camion_US',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inspeccion', models.CharField(max_length=20, verbose_name='inspecci\xf3n')),
                ('expira', models.DateField(unique=True, verbose_name='vencimiento de inspecci\xf3n')),
                ('camion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Camion')),
            ],
        ),
        migrations.CreateModel(
            name='Multas_Camion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_multa', models.DateTimeField(verbose_name='fecha de multa')),
                ('numero', models.IntegerField(unique=True, verbose_name='n\xfamero de multa')),
                ('importe', models.FloatField(verbose_name='importe de multa')),
                ('descripcion', models.TextField(verbose_name='motivo de la multa')),
                ('expira', models.DateField(verbose_name='vigencia de la Multa')),
                ('grua', models.CharField(blank=True, max_length=25, verbose_name='grua')),
                ('importe_grua', models.FloatField(default=0, verbose_name='importe de grua')),
                ('estado', models.BooleanField(choices=[(0, 'Pendiente de pago'), (1, 'Pagado')], default=0, verbose_name='estado de la multa')),
                ('camion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Camion', verbose_name='camion')),
            ],
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(verbose_name='fecha')),
                ('origen', models.CharField(max_length=50, verbose_name='origen')),
                ('destino', models.CharField(max_length=50, verbose_name='destino')),
                ('sellos', models.CharField(max_length=50, verbose_name='sellos')),
                ('estado', models.CharField(max_length=20, verbose_name='estado operaci\xf3n')),
                ('referencia', models.CharField(max_length=15, verbose_name='referencia')),
                ('pedimento', models.CharField(max_length=15, verbose_name='pedimento')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.Caja', verbose_name='caja')),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.Camion', verbose_name='camion')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.Cliente', verbose_name='cliente')),
                ('consignatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Consignatario', verbose_name='consignatario')),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('direccion', models.CharField(max_length=50, verbose_name='direcci\xf3n')),
                ('colonia', models.CharField(choices=[('150 Aniversario', '150 Aniversario'), ('Primero de Mayo', 'Primero de Mayo'), ('20 de Noviembre', '20 de Noviembre'), ('Agronomos', 'Agronomos'), ('Alfonso Gutierrez', 'Alfonso Gutierrez'), ('Alianza Para La Produccion', 'Alianza Para La Produccion'), ('Alijadores', 'Alijadores'), ('Altavista', 'Altavista'), ('America 1', 'America 1'), ('America 2', 'America 2'), ('America 3', 'America 3'), ('America 4', 'America 4'), ('America 5', 'America 5'), ('America 6', 'America 6'), ('America 7', 'America 7'), ('America 8', 'America 8'), ('America 9', 'America 9'), ('America 10', 'America 10'), ('America 11', 'America 11'), ('America 12', 'America 12'), ('Americo Villarreal Guerra', 'Americo Villarreal Guerra'), ('Ampliaci\xf3n Tercer Milenio', 'Ampliaci\xf3n Tercer Milenio'), ('Anahuac', 'Anahuac'), ('Anahuac Sur', 'Anahuac Sur'), ('Anexo Reforma Urbana', 'Anexo Reforma Urbana'), ('Arturo Cortes Villada', 'Arturo Cortes Villada'), ('Ayuntamiento 77', 'Ayuntamiento 77'), ('Balcones del Boulevard', 'Balcones del Boulevard'), ('Balcones del Valle', 'Balcones del Valle'), ('Bellavista', 'Bellavista'), ('Bertha de Avellano', 'Bertha de Avellano'), ('Blanca Navidad', 'Blanca Navidad'), ('Bonanza', 'Bonanza'), ('Bosques del Sur', 'Bosques del Sur'), ('Buenavista', 'Buenavista'), ('Buenos Aires', 'Buenos Aires'), ('Burocratas', 'Burocratas'), ('Campesina', 'Campesina'), ('Campestre', 'Campestre'), ('Candelario Perales', 'Candelario Perales'), ('Carlos Benjamin Galvan Maytorera', 'Carlos Benjamin Galvan Maytorera'), ('Casa Linda', 'Casa Linda'), ('Central 2000', 'Central 2000'), ('Central de Carga', 'Central de Carga'), ('Centro Comercial Reforma', 'Centro Comercial Reforma'), ('Cereso', 'Cereso'), ('Claudette', 'Claudette'), ('Club Campestre Ribera del Bravo', 'Club Campestre Ribera del Bravo'), ('Club de Leones', 'Club de Leones'), ('Cnop', 'Cnop'), ('Colinas Del Sur Oriente', 'Colinas Del Sur Oriente'), ('Colinas Del Sur Poniente', 'Colinas Del Sur Poniente'), ('Colinas de San Javier', 'Colinas de San Javier'), ('Colorines', 'Colorines'), ('Concordia', 'Concordia'), ('Constitucional', 'Constitucional'), ('Cuartel Militar Macario Zamora', 'Cuartel Militar Macario Zamora'), ('Daniel Covarrubias', 'Daniel Covarrubias'), ('Del Maestro', 'Del Maestro'), ('Del Valle', 'Del Valle'), ('Don Ramon Salcido', 'Don Ramon Salcido'), ('Eden Country Villas', 'Eden Country Villas'), ('El Bayito', 'El Bayito'), ('El Campanario', 'El Campanario'), ('El Caporal', 'El Caporal'), ('El Capulin', 'El Capulin'), ('El Caracol', 'El Caracol'), ('El Cortijo', 'El Cortijo'), ('Electricistas', 'Electricistas'), ('El Ed\xe9n', 'El Ed\xe9n'), ('El Frances y Buenos Aires', 'El Frances y Buenos Aires'), ('El Nogal', 'El Nogal'), ('El Pedregal Residencial', 'El Pedregal Residencial'), ('El Progreso', 'El Progreso'), ('El Remolino', 'El Remolino'), ('El Rio', 'El Rio'), ('El Triunfo', 'El Triunfo'), ('Emiliano Zapata', 'Emiliano Zapata'), ('Endulzadora PEMEX', 'Endulzadora PEMEX'), ('Enrique Cardenas Gonzalez', 'Enrique Cardenas Gonzalez'), ('Ferrocarril', 'Ferrocarril'), ('Ferrocarrilera', 'Ferrocarrilera'), ('FOVISSSTE Benito Juarez', 'FOVISSSTE Benito Juarez'), ('FOVISSSTE Las Alazanas', 'FOVISSSTE Las Alazanas'), ('Francisco Villa', 'Francisco Villa'), ('Francisco Villa 2', 'Francisco Villa 2'), ('Gilberto Montemayor Quintanilla', 'Gilberto Montemayor Quintanilla'), ('Gonzalez', 'Gonzalez'), ('Gran Boulevard', 'Gran Boulevard'), ('Granjas Economicas 1', 'Granjas Economicas 1'), ('Granjas Economicas 2', 'Granjas Economicas 2'), ('Granjas Guzman', 'Granjas Guzman'), ('Granjas Regina', 'Granjas Regina'), ('Granjas Trevino', 'Granjas Trevino'), ('Guerrero', 'Guerrero'), ('Guerreros Del Sol', 'Guerreros Del Sol'), ('Hacienda de La Concordia', 'Hacienda de La Concordia'), ('Hacienda J. Longoria', 'Hacienda J. Longoria'), ('Haciendas de San Agustin', 'Haciendas de San Agustin'), ('Hidalgo', 'Hidalgo'), ('Hipodromo', 'Hipodromo'), ('Independencia', 'Independencia'), ('INFONAVIT Benito Juarez', 'INFONAVIT Benito Juarez'), ('INFONAVIT Fundadores', 'INFONAVIT Fundadores'), ('Insurgentes', 'Insurgentes'), ('Itavu', 'Itavu'), ('Jardan', 'Jardan'), ('Jardines de la Hacienda', 'Jardines de la Hacienda'), ('Jardan Juvencia', 'Jardan Juvencia'), ('Jesus Garcia', 'Jesus Garcia'), ('Juarez', 'Juarez'), ('Junta Federal de Mejoras Materiales', 'Junta Federal de Mejoras Materiales'), ('La Concordia', 'La Concordia'), ('La Cruz', 'La Cruz'), ('La Esperanza', 'La Esperanza'), ('La Fe', 'La Fe'), ('Lagos', 'Lagos'), ('La Joya', 'La Joya'), ('La Paz', 'La Paz'), ('Las Alamedas', 'Las Alamedas'), ('Las Alazanas', 'Las Alazanas'), ('La Sandia', 'La Sandia'), ('Las Arboledas', 'Las Arboledas'), ('Las Cumbres', 'Las Cumbres'), ('Las Flores', 'Las Flores'), ('Las Lomas', 'Las Lomas'), ('Las Piedritas', 'Las Piedritas'), ('Las Torres', 'Las Torres'), ('Las Vi\xf1as', 'Las Vi\xf1as'), ('Lic. Daniel Hernandez Isais', 'Lic. Daniel Hernandez Isais'), ('Lic. Luis Donaldo Colosio', 'Lic. Luis Donaldo Colosio'), ('Loma Bonita', 'Loma Bonita'), ('Lomas del Poniente', 'Lomas del Poniente'), ('Lomas Del Popo', 'Lomas Del Popo'), ('Lomas Del Rey', 'Lomas Del Rey'), ('Lomas Del Rio', 'Lomas Del Rio'), ('Lomas del Rosario', 'Lomas del Rosario'), ('Los Agaves', 'Los Agaves'), ('Los Alamos', 'Los Alamos'), ('Los Angeles', 'Los Angeles'), ('Los Arcos', 'Los Arcos'), ('Los Artistas', 'Los Artistas'), ('Los Aztecas', 'Los Aztecas'), ('Los Cantaros', 'Los Cantaros'), ('Los Cerezos', 'Los Cerezos'), ('Los Ciruelos', 'Los Ciruelos'), ('Los Encinos', 'Los Encinos'), ('Los Fresnos', 'Los Fresnos'), ('Los Garza', 'Los Garza'), ('Los Olivos', 'Los Olivos'), ('Los Presidentes', 'Los Presidentes'), ('Los Sanchez', 'Los Sanchez'), ('Los Virreyes', 'Los Virreyes'), ('Maclovio Herrera', 'Maclovio Herrera'), ('Madero', 'Madero'), ('Manuel Cavazos Lerma', 'Manuel Cavazos Lerma'), ('Manuel Martinez Mendez', 'Manuel Martinez Mendez'), ('Maria Del Pilar Martinez Munoz', 'Maria Del Pilar Martinez Munoz'), ('Maria Luisa', 'Maria Luisa'), ('Matamoros', 'Matamoros'), ('Mexico', 'Mexico'), ('Dr Mier', 'Dr Mier'), ('Miguel Aleman', 'Miguel Aleman'), ('Militar', 'Militar'), ('Mirador', 'Mirador'), ('Mision de San Mauricio', 'Mision de San Mauricio'), ('Morelos', 'Morelos'), ('Naciones Unidas', 'Naciones Unidas'), ('Nueva Era', 'Nueva Era'), ('Nueva Espana', 'Nueva Espana'), ('Nueva Victoria', 'Nueva Victoria'), ('Centro', 'Centro'), ('Quetzalcoatl', 'Quetzalcoatl'), ('Nuevo Milenio', 'Nuevo Milenio'), ('Ojo Caliente', 'Ojo Caliente'), ('Othon Chavez', 'Othon Chavez'), ('Palacios', 'Palacios'), ('Palmares', 'Palmares'), ('2 Laredos', '2 Laredos'), ('FINSA', 'FINSA'), ('Longoria', 'Longoria'), ('Oradel', 'Oradel'), ('Rio Bravo', 'Rio Bravo'), ('Rio Grande', 'Rio Grande'), ('Americas', 'Americas'), ('Pavorreales', 'Pavorreales'), ('Pedregal', 'Pedregal'), ('Pe\xf1a Benavides', 'Pe\xf1a Benavides'), ('Postal', 'Postal'), ('Praderas del Mezquital', 'Praderas del Mezquital'), ('Privanzas Sector Alameda', 'Privanzas Sector Alameda'), ('Recinto Fiscal', 'Recinto Fiscal'), ('Reforma Urbana', 'Reforma Urbana'), ('Reservas Territoriales', 'Reservas Territoriales'), ('Residencial Longoria', 'Residencial Longoria'), ('Riberas del Bravo', 'Riberas del Bravo'), ('Roma', 'Roma'), ('Rosita', 'Rosita'), ('San Andres', 'San Andres'), ('Saneva', 'Saneva'), ('San Jose', 'San Jose'), ('San Patricio', 'San Patricio'), ('San Rafael', 'San Rafael'), ('Santa Anita', 'Santa Anita'), ('Santa Cecilia', 'Santa Cecilia'), ('Santa Elena', 'Santa Elena'), ('Santa Martha', 'Santa Martha'), ('Santiago M. Belden', 'Santiago M. Belden'), ('Sistema de Agua y Saneamiento', 'Sistema de Agua y Saneamiento'), ('Sistema Merlin', 'Sistema Merlin'), ('Solidaridad', 'Solidaridad'), ('SUTERM I', 'SUTERM I'), ('SUTERM II', 'SUTERM II'), ('Tamaulipas', 'Tamaulipas'), ('Tercer Milenio', 'Tercer Milenio'), ('Tinajitas', 'Tinajitas'), ('Toboganes', 'Toboganes'), ('Tulipanes', 'Tulipanes'), ('Unidad Nacional', 'Unidad Nacional'), ('Union', 'Union'), ('Union Del Recuerdo', 'Union Del Recuerdo'), ('Valle Dorado', 'Valle Dorado'), ('Valle Elizondo', 'Valle Elizondo'), ('Valle Real', 'Valle Real'), ('Valles de Anahuac', 'Valles de Anahuac'), ('Valles del Paraiso', 'Valles del Paraiso'), ('Vamos Tamaulipas', 'Vamos Tamaulipas'), ('Vamos Tamaulipas', 'Vamos Tamaulipas'), ('Vicente Mendoza', 'Vicente Mendoza'), ('Victoria', 'Victoria'), ('Villa Del Lago', 'Villa Del Lago'), ('Villas de la Concordia', 'Villas de la Concordia'), ('Villas de La Fe', 'Villas de La Fe'), ('Villas del Oradel', 'Villas del Oradel'), ('Villas del Progreso', 'Villas del Progreso'), ('Villas Del Sol', 'Villas Del Sol'), ('Villas de San Francisco', 'Villas de San Francisco'), ('Villas de San Miguel', 'Villas de San Miguel'), ('Vista Hermosa', 'Vista Hermosa'), ('Viveros', 'Viveros'), ('Viviendas Unidas', 'Viviendas Unidas'), ('Voluntad y Trabajo', 'Voluntad y Trabajo'), ('Zaragoza', 'Zaragoza'), ('Zona de Tolerancia', 'Zona de Tolerancia')], max_length=20, verbose_name='colonia')),
                ('ciudad', models.CharField(default='Nuevo Laredo', max_length=20, verbose_name='ciudad')),
                ('pasaporte', models.CharField(max_length=15, verbose_name='pasaporte')),
                ('telefono', models.CharField(blank=True, max_length=10, verbose_name='tel\xe9fono')),
                ('radio', models.CharField(blank=True, max_length=12, verbose_name='radio')),
                ('celular', models.CharField(blank=True, max_length=10, verbose_name='celular')),
                ('estado', models.BooleanField(default=False, help_text='Seleccione estado (Libre-Ocupado)', verbose_name='estado')),
                ('nss', models.CharField(max_length=30, verbose_name='seguro social')),
                ('curp', models.CharField(max_length=30, verbose_name='CURP')),
                ('rfc', models.CharField(max_length=30, verbose_name='registro de contribuyentes')),
                ('visa', models.CharField(max_length=15, verbose_name='visa')),
                ('visa_expira', models.DateField(verbose_name='vencimiento de visa')),
                ('fast', models.CharField(max_length=15, verbose_name='cruse FAST')),
                ('fast_expira', models.DateField(verbose_name='vencimiento de FAST')),
                ('licencia', models.CharField(max_length=25, verbose_name='licencia')),
                ('licencia_expira', models.DateField(verbose_name='vencimiento de licencia')),
                ('medico', models.CharField(max_length=25, verbose_name='seguro medico')),
                ('medico_expira', models.DateField(verbose_name='vencimiento de seguro medico')),
                ('camion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='system.Camion')),
            ],
        ),
        migrations.CreateModel(
            name='Orden_Reparacion_Camion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255, verbose_name='descripcion')),
                ('tipo', models.CharField(choices=[('P', 'Cambio de Pieza'), ('MO', 'Mano de obra')], max_length=2, verbose_name='tipo de reparacion')),
                ('cantidad', models.IntegerField(verbose_name='cantida')),
                ('provedor', models.CharField(max_length=150, verbose_name='provedor')),
                ('factura', models.CharField(max_length=17, verbose_name='factura')),
                ('costo_r_mx', models.FloatField(verbose_name='costo MX')),
                ('costo_r_usd', models.FloatField(verbose_name='costo US')),
                ('tipo_pago', models.CharField(choices=[('E', 'Efectivo'), ('CH', 'Cheque')], max_length=2, verbose_name='tipo de pago')),
            ],
        ),
        migrations.CreateModel(
            name='Patio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('direccion', models.CharField(max_length=70, verbose_name='direcci\xf3n')),
                ('pais', models.CharField(choices=[('US', 'United States'), ('MX', 'Mexico'), ('CA', 'Canada')], max_length=20, verbose_name='pa\xeds')),
                ('linea', models.CharField(max_length=50, verbose_name='linea')),
                ('telefono', models.CharField(max_length=20, verbose_name='telefono')),
                ('contacto', models.CharField(max_length=50, verbose_name='contacto')),
                ('observaciones', models.TextField(verbose_name='observaciones')),
                ('latitud', models.CharField(max_length=50, verbose_name='latitud')),
                ('longitud', models.CharField(max_length=50, verbose_name='longitud')),
            ],
        ),
        migrations.CreateModel(
            name='Reparacion_Camion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='fecha de terminaci\xf3n')),
                ('rotura', models.CharField(max_length=255, verbose_name='rotura')),
                ('costo_usd', models.FloatField(verbose_name='costo USD')),
                ('costo_mx', models.FloatField(verbose_name='costo MX')),
                ('estado', models.BooleanField(default=False, help_text='Seleccione el estado (Iniciada-Terminada)', verbose_name='estado reparaci\xf3n')),
                ('detecto_fecha', models.DateTimeField(verbose_name='fecha de detecci\xf3n')),
                ('supervisor_fecha', models.DateTimeField(verbose_name='fecha de supervici\xf3n')),
                ('autorizo_fecha', models.DateTimeField(verbose_name='fecha de autorizaci\xf3n')),
                ('autorizo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizo_user', to=settings.AUTH_USER_MODEL, verbose_name='autorizo')),
                ('camion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Camion', verbose_name='camion')),
                ('detecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.Operador', verbose_name='detector de rotura')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_user', to=settings.AUTH_USER_MODEL, verbose_name='supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='Seguromx_Camion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seguromx', models.CharField(max_length=20, verbose_name='seguro MX')),
                ('expira_seguromx', models.DateField(verbose_name='vencimiento de seguro MX')),
                ('camion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smx_camion', to='system.Camion')),
            ],
        ),
        migrations.CreateModel(
            name='Segurous_Camion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('segurous', models.CharField(max_length=20, verbose_name='seguro US')),
                ('expira_segurous', models.DateField(verbose_name='vencimiento de seguro US')),
                ('camion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sus_camion', to='system.Camion')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('T', 'Trompo'), ('TUS', 'Trompo US'), ('TMX', 'Trompo MX'), ('R', 'Repartos'), ('ML', 'Movimiento local'), ('MLMX', 'Movimiento local MX'), ('MLUS', 'Movimiento local US'), ('MLR', 'Movimiento local Rampa'), ('EXP', 'Exportaci\xf3n'), ('EXPV', 'Exportaci\xf3n vacia'), ('IMP', 'Importaci\xf3n'), ('IMPV', 'Importaci\xf3n vacia'), ('MP', 'Movimiento de patio'), ('MPUS', 'Movimiento de patio US'), ('MPMX', 'Movimiento de patio MX'), ('MP', 'Movimiento de inspecci\xf3n'), ('CF', 'Cruze en falso'), ('CFMX', 'Cruze en falso MX'), ('CFUS', 'Cruze en falso US')], max_length=70, verbose_name='tipo de servicio')),
                ('dsemana', models.CharField(max_length=7, verbose_name='d\xedas de la semana')),
                ('aduana', models.CharField(choices=[('LRD-240', 'Laredo-240'), ('COL-800', 'Colombia-800')], max_length=50, verbose_name='aduana')),
                ('remolque', models.CharField(choices=[('NO', 'No aplica'), ('CS', 'Caja seca'), ('CSE', 'Caja seca Esp.'), ('CSV', 'aja seca vacia'), ('CSH', 'Caja seca Hazmat'), ('C', 'Contenedor'), ('P', 'Plataforma'), ('PE', 'Plataforma Esp.'), ('SL', 'Semi Lowboy'), ('L', 'Lowboy'), ('PP', 'Poppies'), ('R', 'Refrigerada'), ('PA', 'Pipa')], max_length=50, verbose_name='remolque')),
                ('importemx', models.FloatField(verbose_name='importe MX')),
                ('importeusd', models.FloatField(verbose_name='importe USD')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Tasa_Cambio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(unique=True)),
                ('tasa', models.FloatField(verbose_name='tasa de cambio')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion_Camion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('camion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uc_camion', to='system.Camion')),
            ],
        ),
        migrations.CreateModel(
            name='Verificacion_Camion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('verificacion', models.CharField(max_length=20, verbose_name='verificaci\xf3n')),
                ('expira', models.DateField(unique=True, verbose_name='vencimiento de verificaci\xf3n')),
                ('camion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Camion')),
            ],
            options={
                'verbose_name': 'verificaci\xf3n camion',
                'verbose_name_plural': 'verificaci\xf3n camion',
            },
        ),
        migrations.AddField(
            model_name='orden_reparacion_camion',
            name='reparacion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Reparacion_Camion', verbose_name='reparaci\xf3n ID'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.Operador', verbose_name='operador'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.Servicio', verbose_name='servicio'),
        ),
        migrations.AddField(
            model_name='caja',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Cliente'),
        ),
    ]
