# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 02:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sello_Operacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sello', models.CharField(max_length=50, verbose_name='sello')),
                ('fecha', models.DateTimeField(help_text='Fecha')),
                ('observaciones', models.TextField(verbose_name='observaciones')),
            ],
        ),
        migrations.RemoveField(
            model_name='operacion',
            name='sellos',
        ),
        migrations.AlterField(
            model_name='operacion',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente autorizaci\xf3n'), ('I', 'Iniciada'), ('T', 'Terminada')], default='P', max_length=20, verbose_name='estado operaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 29, 21, 21, 54, 924000)),
        ),
        migrations.AddField(
            model_name='sello_operacion',
            name='operacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.Operacion', verbose_name='operacion'),
        ),
    ]
