# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 22:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='retencion',
            field=models.BooleanField(default=False, verbose_name='aplica Retencion del 4%'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pais',
            field=models.CharField(choices=[('US', 'United States'), ('MX', 'Mexico')], max_length=20, verbose_name='pa\xeds'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rfc',
            field=models.CharField(blank=True, help_text='Registro Federal de Contribuyentes', max_length=13, validators=[django.core.validators.RegexValidator(message='C\xf3digo RFC invalido', regex='^([A-Z\xd1&]{3,4}) ?(?:- ?)?(\\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\\d|3[01])) ?(?:- ?)?([A-Z\\d]{2})([A\\d])$')], verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tax',
            field=models.CharField(blank=True, max_length=45, verbose_name='tax'),
        ),
        migrations.AlterField(
            model_name='patio',
            name='pais',
            field=models.CharField(choices=[('US', 'United States'), ('MX', 'Mexico')], max_length=20, verbose_name='pa\xeds'),
        ),
    ]
