# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 18:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='pagada',
        ),
        migrations.AddField(
            model_name='operacion',
            name='facturada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='operador',
            name='pasaporte',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Numero de pasaporte invalido', regex='^(\\d{2})(\\d{2})(\\d{2})\\d{5}$')], verbose_name='pasaporte'),
        ),
    ]
