# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 22:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0002_auto_20170516_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=20, verbose_name='pa\xeds')),
                ('estado', models.CharField(max_length=20, verbose_name='estado')),
                ('direccion', models.CharField(max_length=50, verbose_name='direcci\xf3n')),
                ('cpostal', models.CharField(max_length=7, verbose_name='c\xf3digo postal')),
                ('rfc', models.CharField(max_length=15, verbose_name='rfc')),
                ('telefono', models.CharField(blank=True, max_length=10, verbose_name='tel\xe9fono')),
                ('contacto', models.CharField(max_length=50, verbose_name='contacto')),
                ('descripcion', models.CharField(max_length=255, verbose_name='descripcion')),
                ('zip', models.CharField(max_length=7, verbose_name='c\xf3digo zip')),
                ('tax', models.CharField(max_length=45, verbose_name='tax')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='ubicacion_camion',
            name='ubicacion',
            field=models.CharField(max_length=100),
        ),
    ]
