# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-01 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20171227_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('millaje', models.IntegerField(verbose_name='millaje')),
                ('litros', models.FloatField(verbose_name='litros')),
                ('fecha', models.DateTimeField()),
                ('camion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comb_camion', to='system.Camion')),
                ('operador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comb_operador', to='system.Operador')),
            ],
        ),
    ]
