# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20171001_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='fecha_estado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
