# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20171022_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concepto_operacion',
            name='cantidad',
        ),
    ]
