# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_factura_pagada'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
