# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20171001_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento_operacion',
            name='fecha_terminacion',
            field=models.DateTimeField(blank=True, help_text='fecha de terminaci\xf3n', null=True),
        ),
    ]
