# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 02:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20170929_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 29, 21, 40, 1, 764000)),
        ),
    ]
