# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_servicio_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='total_mx',
            field=models.FloatField(blank=True, null=True, verbose_name='total MX'),
        ),
        migrations.AddField(
            model_name='factura',
            name='total_usd',
            field=models.FloatField(blank=True, null=True, verbose_name='total USD'),
        ),
    ]
