# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 21:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20170929_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 29, 21, 43, 46, 6000)),
        ),
    ]
