# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20171022_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepto_operacion',
            name='concepto',
            field=models.CharField(max_length=50, verbose_name='concepto'),
        ),
        migrations.AlterField(
            model_name='concepto_operacion',
            name='observaciones',
            field=models.TextField(verbose_name='observaciones'),
        ),
    ]
