# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20171022_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='concepto_operacion',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de concepto'),
        ),
    ]
