# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 22:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20170929_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 29, 22, 4, 19, 312000)),
        ),
        migrations.AlterField(
            model_name='sello_operacion',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='observaciones'),
        ),
    ]
