# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20171015_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='importemx',
            field=models.FloatField(blank=True, null=True, verbose_name='importe MX'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='importeusd',
            field=models.FloatField(blank=True, null=True, verbose_name='importe USD'),
        ),
    ]
