# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_concepto_operacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepto_operacion',
            name='fecha',
            field=models.DateTimeField(verbose_name='fecha de concepto'),
        ),
    ]
