# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20171028_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concepto_operacion',
            old_name='fecha',
            new_name='fecha_concepto',
        ),
    ]
