# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 21:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_auto_20171028_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacion',
            name='fecha',
        ),
        migrations.AddField(
            model_name='operacion',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 28, 21, 0, 23, 671000), verbose_name='fecha de inicio'),
        ),
    ]
