# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_auto_20171028_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='fecha_inicio',
            field=models.DateTimeField(verbose_name='fecha de inicio'),
        ),
    ]
