# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_auto_20171029_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('importe', models.FloatField(verbose_name='importe a pagar')),
                ('fecha', models.DateTimeField(verbose_name='fecha de pago')),
                ('metodo', models.CharField(choices=[('C', 'Cheque'), ('T', 'Transferencia')], max_length=1, verbose_name='metodo de pago')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobado'), ('C', 'Cancelado')], default='P', max_length=1)),
                ('cuenta', models.CharField(choices=[('IBC', 'IBC'), ('BMEX', 'Banamex'), ('GRT', 'Grt-transfer')], max_length=4, verbose_name='Cuenta de deposito')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
            ],
        ),
        migrations.AlterField(
            model_name='factura',
            name='tasa_cambio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pagos',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.Factura', verbose_name='factura'),
        ),
    ]
