# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_auto_20171107_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('A', 'Abierta'), ('C', 'Cancelada'), ('P', 'Pagada')], default='A', max_length=1),
        ),
    ]
