# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_auto_20171114_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='moneda',
            field=models.CharField(choices=[('MXN', 'Pesos'), ('USD', 'Dollar')], default='MXN', max_length=3),
        ),
    ]
