# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_pagos_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='moneda',
            field=models.CharField(choices=[('MXN', 'Pesos'), ('USD', 'Dollar')], max_length=3),
        ),
    ]
